version: "2"
linters:
  default: none
  enable:
    - loglint
  settings:
    custom:
      loglint:
        type: module
        description: "checks log messages style"
        settings:
          check-lowercase: true
          check-english: true
          check-special-chars: true
          check-sensitive: true
          extra-patterns:
            - "credit_card"
            - "ssn"